### ISSUE TITLE
error while loading calibration file

### ISSUE THREAD

**Issue by Yeah2333** [zjhthu/OANet#19]
when i run yfcc.py,there is a error. how to fix it?

`../raw_data/yfcc100m//buckingham_palace/test
dump dir ../data_dump//buckingham_palace/sift-2000/test
Error while loading ../raw_data/yfcc100m//buckingham_palace/test/calibration/calibration_000001.h5
Traceback (most recent call last):
  File "/media/data/wzy/OANet/dump_match/utils.py", line 98, in loadh5
    raise e
  File "/media/data/wzy/OANet/dump_match/utils.py", line 95, in loadh5
    dict_from_file = readh5(h5file)
  File "/media/data/wzy/OANet/dump_match/utils.py", line 111, in readh5
    dict_from_file[_key] = h5node[_key].value
AttributeError: 'Dataset' object has no attribute 'value'

Process finished with exit code 1`

**Comment by Yeah2333** [comment]
i have finish this error , need change dict_from_file[_key] = h5node[_key].value to dict_from_file[_key] = h5node[_key][:]
